### ISSUE TITLE
process names may contain spaces

### ISSUE THREAD

**Issue by thrig** [Microsoft/ProcDump-for-Linux#8]
https://github.com/Microsoft/ProcDump-for-Linux/blob/master/src/Process.c#L51

seems somewhat dubious given that the process name can contain spaces e.g.

    perl -e '$0="string parsing in C is hard"; say $$; sleep 9999'

which I believe will result in a `proc->comm` of `"strin"` and then who knows what for the subsequent tokens.

References & Related Readings

CVE-2017-1000367

**Comment by jahabibi** [comment]
Confirmed this is a bug I can recreate it. We will address this in the next minor release.

**Comment by thrig** [comment]
reading from two different files in `/proc` may be a race condition if the process goes away between the two reads. there is also the `/proc/$$/status` file...

**Comment by josalem** [comment]
You make a good point.  The original intent of using `stat` vs `status` was that `stat` is the more "computer readable" format for the information, but as you point out, `status` does handle isolating the name for us in a better manner. 

#17

**Comment by josalem** [comment]
Having done a little more reading on how the kernel handles names of processes, I think it is actually fine to read from `stat` and `cmdline`.  

The actual kernel struct that represents a process in the scheduler (to my understanding, this is where all the information in `stat` comes from) has comm as [`char comm[TASK_COMM_LEN]`](https://github.com/torvalds/linux/blob/bbecb1cfcca55f98cfcb62fa36a32d79975d8816/include/linux/sched.h#L761) where [`TASK_COMM_LEN` is defined as 16](https://github.com/torvalds/linux/blob/bbecb1cfcca55f98cfcb62fa36a32d79975d8816/include/linux/sched.h#L167) (really it's 15 + the `\0`).

This means that if we want to display the "full name" of the process, we do actually need to read from multiple sources.  Since the `/proc/[pid]` pseudo-directory will only exist as long as the process is executing, we aren't really faced with a breaking race condition.  If a read to any of the pseudo files inside the directory fails, we simply head to exit code path per normal procedure since Procdump wouldn't be able to continue executing anyway.  We can reduce double reads though, by only reading that full name once and caching it aside.  Then every subsequent read is just to `stat`, and we can simply read from `(` to the last `)` (in case the process has ( or ) in its name).
